general: 
  ingress_host: k8s-test-loadbalancer.local
  plex_ingress_host: plex.local
  image_tag: latest
  #UID to run the process with
  puid: 1000
  #GID to run the process with
  pgid: 1000
  #Name, size and eventual SC of needed PVC
  storage:
    pvcName: mykubeapps-pvc
    size: 600Gi
    pvcStorageClass: managed-nfs-storage
    nfs: true
    nfsServer: "192.168.1.228"
    nfsPath: /export/drive

sonarr:
  container: 
    nodeSelector: {}
    port: 8989
  service:
    type: ClusterIP
    port: 8989
    nodePort: 
    extraLBService: false 
    # Defines an additional LB service, requires cloud provider service or MetalLB 

  ingress:
    enabled: true
    annotations: {}
    path: /sonarr
    tls:
      enabled: false
      secretName: ""

radarr:
  container: 
    nodeSelector: {}
    port: 7878
  service:
    type: ClusterIP
    port: 7878
    nodePort: 
    extraLBService: false 
    # Defines an additional LB service, requires cloud provider service or MetalLB 

  ingress:
    enabled: true
    annotations: {}
    path: /radarr
    tls:
      enabled: false
      secretName: ""
  
jackett:
  container: 
    nodeSelector: {}
    port: 9117
  service:
    type: ClusterIP
    port: 9117
    nodePort: 
    extraLBService: false 
    # Defines an additional LB service, requires cloud provider service or MetalLB 
  ingress:
    enabled: true
    annotations: {}
    path: /jackett
    tls:
      enabled: false
      secretName: ""
  
transmission:
  container: 
    nodeSelector: {}
    port: 9091
  service:
    type: ClusterIP
    port: 9091
    nodePort: 
    # Defines an additional LB service, requires cloud provider service or MetalLB 
    extraLBService: false 
  ingress:
    enabled: true
    annotations: {}
    path: /transmission
    tls:
      enabled: false
      secretName: ""

plex:
  claim: claim-EazK_asskQfY3yN5HJMj
  advertise_ip: "plex.mykubeapps.local:32400"
  container:
    nodeSelector: {}
    port: 32400
  ingress:
    annotations: {}
    enabled: true
    tls:
      enabled: false
      secretName: ""
  replicaCount: 1
  service:
    extraLBService: false
    nodePort: 32400
    port: 32400
    type: NodePort
