apiVersion: v1
data:
  ServerConfig.json: |
    {
      "BasePathOverride": "{{ .Values.jackett.ingress.path }}"
    }
  init-jackett.sh: |
    #!/bin/bash
    cp -n /init-jackett/ServerConfig.json /jackett-config/ServerConfig.json
kind: ConfigMap
metadata:
  name: init-jackett-cm
