{{- if .Values.jackett.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
  labels:
    {{- include "mykubeapps.labels" . | nindent 4 }}
  {{- with .Values.jackett.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{ if .Values.jackett.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.general.ingress_host | quote }}
      secretName: {{ .Values.jackett.ingress.tls.secretName }}
{{ end }}     
  rules:
    - host: {{ .Values.general.ingress_host | quote }}
      http:
        paths:
          - path: {{ .Values.jackett.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: jackett
                port:
                  number: {{ .Values.jackett.service.port }}
{{ end }}     
