{{ if .Values.general.storage.nfs }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mykubeapps-pv
spec:
  capacity:
    storage: {{ .Values.general.storage.size }} 
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: {{ .Values.general.storage.nfsServer }}
    path: {{ .Values.general.storage.nfsPath }}
{{ end }}