apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    {{- include "mykubeapps.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.plex.replicaCount }}
  selector:
    matchLabels:
      {{- include "mykubeapps.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mykubeapps.selectorLabels" . | nindent 8 }}
        app: plex
    spec:
      volumes:
        - name: mykubeapps-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: plex-config
          image: "docker.io/linuxserver/plex:{{ .Values.general.image_tag }}"
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: {{ .Values.plex.container.port }}
            initialDelaySeconds: 20
            periodSeconds: 15
          ports:
            - name: plex-port
              containerPort: {{ .Values.plex.container.port }}
              protocol: TCP
          volumeMounts:
            - name: mykubeapps-volume
              mountPath: "/config"
              subPath: "config/plex"
            - name: mykubeapps-volume
              mountPath: "Media/Movies"
              subPath: "/Movies"
            - name: mykubeapps-volume
              mountPath: "/tv"
              subPath: "Media/TV"
      {{- with .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

