apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    {{- include "mykubeapps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.plex.service.type }}
  ports:
    - port: {{ .Values.plex.service.port }}
      targetPort: {{ .Values.plex.container.port }}
      protocol: TCP
      name: plex-port
{{ if eq .Values.plex.service.type "NodePort" }}
      nodePort: {{ .Values.plex.service.nodePort }}
{{ end }}
  selector:
    app: plex

---
{{ if .Values.plex.service.extraLBService }}
apiVersion: v1
kind: Service
metadata:
  name: plex-lb
  labels:
    {{- include "mykubeapps.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.plex.service.port }}
      targetPort: {{ .Values.plex.container.port }}
      protocol: TCP
      name: plex-port
  selector:
    app: plex
{{ end }}