apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    {{- include "mykubeapps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sonarr.service.type }}
  ports:
    - port: {{ .Values.sonarr.service.port }}
      targetPort: {{ .Values.sonarr.container.port }}
      protocol: TCP
{{ if eq .Values.sonarr.service.type "NodePort" }}
      nodePort: {{ .Values.sonarr.service.nodePort }}
{{ end }}
      name: sonarr-port
  selector:
    app: sonarr

---
{{ if .Values.sonarr.service.extraLBService }}
apiVersion: v1
kind: Service
metadata:
  name: sonarr-lb
  labels:
    {{- include "mykubeapps.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.sonarr.service.port }}
      targetPort: {{ .Values.sonarr.container.port }}
      protocol: TCP
      name: sonarr-port
  selector:
    app: sonarr
{{ end }}