apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    {{- include "mykubeapps.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mykubeapps.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mykubeapps.selectorLabels" . | nindent 8 }}
        app: sonarr
    spec:
      initContainers:
        - name: config-sonarr
          image: docker.io/ubuntu:groovy
          command: ["/init-sonarr/init-sonarr.sh"]
          volumeMounts:
            - mountPath: /init-sonarr
              name: init-files-sonarr
            - mountPath: /sonarr-config
              name: mediaserver-volume
              subPath: "config/sonarr"
          securityContext:
            runAsUser: {{ .Values.general.puid }}
            runAsGroup: {{ .Values.general.pgid }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: sonarr-config
          image: "docker.io/linuxserver/sonarr:{{ .Values.general.image_tag }}"
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: {{ .Values.sonarr.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          ports:
            - name: sonarr-port
              containerPort: {{ .Values.sonarr.container.port }}
              protocol: TCP
          volumeMounts:
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "config/sonarr"
            - name: mediaserver-volume
              mountPath: "/downloads"
              subPath: "downloads/transmission"
            - name: mediaserver-volume
              mountPath: "/tv"
              subPath: "media/tv"
      volumes:
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.general.storage.pvcName }}
        - name: init-files-sonarr
          configMap:
            defaultMode: 493
            name: init-sonarr-cm
      {{- with .Values.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
