apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    {{- include "mykubeapps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.transmission.service.type }}
  ports:
    - port: {{ .Values.transmission.service.port }}
      targetPort: {{ .Values.transmission.container.port }}
      protocol: TCP
      name: trans-port
{{ if eq .Values.transmission.service.type "NodePort" }}
      nodePort: {{ .Values.transmission.service.nodePort }}
{{ end }}
  selector:
    app: transmission

---
{{ if .Values.transmission.service.extraLBService }}
apiVersion: v1
kind: Service
metadata:
  name: transmission-lb
  labels:
    {{- include "mykubeapps.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.transmission.service.port }}
      targetPort: {{ .Values.transmission.container.port }}
      protocol: TCP
      name: trans-port
  selector:
    app: transmission
{{ end }}
